FROM nginx:alpine-slim

LABEL  maintainer="Maedeh" \
       version="1.0.0"\
       description="Nginx Static WebServer"

WORKDIR /usr/share/nginx/html
RUN rm -rf ./*

COPY . .

HEALTHCHECK  --interval=30s --timeout=3s  --retries=3 \
	CMD wget -qO- http://localhost/ || exit 1


EXPOSE 80

CMD ["nginx","-g","daemon off;"]







